### ISSUE TITLE
Work on merge of two libraries

### ISSUE THREAD

**Issue by bezmi** [iloveicedgreentea/jvc_projector_improved#13]
Hey mate, I like the work you're doing with this. My own jvc_projector module was recently updated to support the newer models with passwords. In addition to the [develop fork](https://github.com/bezmi/jvc_projector/blob/develop/src/jvc_projector/jvccommands.py) where I was working on (but ran out of time) an async version of the library, I also recently added more robustness and better error checking for the communications protocol in the [improved_commands](https://github.com/bezmi/jvc_projector/tree/improved_commands/src/jvc_projector) branch.

The rationale for the improved_commands branch is to allow specifying a single structure which will allow the code to execute both read and write type commands for that particular feature. I initially tried to retain the `Enum` structures as you have, but it was difficult to specify for commands that would be read only or write only. For the current version which I am still testing, I have settled on using the [dict based structure](https://github.com/bezmi/jvc_projector/blob/c0364f7c22159d793e24d4ca11c738f90f25ce81/src/jvc_projector/jvccommands.py#L210). 

My plan was actually to get back to work on the async version, but I realised that a little more robustness was needed for the `_send_command()` method, which is what lead me down this rabbit hole. I'm not sure async is really even a must here, as the control server on the projector is not really async in any way and we can call synchronous functions from homeassistant using:

```python
# hub.update() is a sync function.
result = await hass.async_add_executor_job(hub.update)
```
Once I've got the commands stuff worked out, I will still work on bringing async into my version. 

Would you be willing to work with me on bringing your changes into the library? I'm mostly asking for a bit of support in testing/validation/debugging with your projector. Since you know python and you have one of the projectors, your insight is very valuable.

**Comment by iloveicedgreentea** [comment]
Hey,

Thank you. The reason I went with Enums is because it made specifying send and receive acks easier and nicer. Async is not necessary per se but its easier to integrate with HA in addition to supporting other front ends. In my quick testing it also was more reliable because it seems to queue commands instead of having them drop off if there are issues, but that might have been unrelated. I am happy to test your changes on my setup, but it might be easier to develop on this library since I am happy with my implementation and its feature complete, IMO. Only thing I want to improve is the reconnect mechanism which is mostly reliable but has edge cases.
